import Foundation

public enum Sheets: String, CaseIterable {
    case AOZArrangement
    case AOZBoss
    case AOZContent
    case AOZContentBriefingBNpc
    case AOZContentBriefingObject
    case AOZReport
    case AOZReportReward
    case AOZScore
    case AOZWeeklyReward
    case Achievement
    case AchievementCategory
    case AchievementHideCondition
    case AchievementKind
    case AchievementTarget
    case Action
    case ActionCastTimeline
    case ActionCastVFX
    case ActionCategory
    case ActionComboRoute
    case ActionComboRouteTransient
    case ActionCostType
    case ActionIndirection
    case ActionInit
    case ActionParam
    case ActionProcStatus
    case ActionSetting
    case ActionTimeline
    case ActionTimelineMove
    case ActionTimelineReplace
    case ActionTransient
    case ActivityFeedButtons
    case ActivityFeedCaptions
    case ActivityFeedGroupCaptions
    case ActivityFeedImages
    case Addon
    case AddonHudSize
    case AddonLayout
    case AddonParam
    case AddonTalkParam
    case AddonTransient
    case AdvancedVibration
    case Adventure
    case AdventureExPhase
    case AetherCurrent
    case AetherCurrentCompFlgSet
    case AetherialWheel
    case Aetheryte
    case AetheryteSystemDefine
    case AetheryteTransient
    case AirshipExplorationLevel
    case AirshipExplorationLog
    case AirshipExplorationParamType
    case AirshipExplorationPart
    case AirshipExplorationPoint
    case AirshipSkyIsland
    case AkatsukiNote
    case AkatsukiNoteString
    case AnimaWeapon5
    case AnimaWeapon5Param
    case AnimaWeapon5PatternGroup
    case AnimaWeapon5SpiritTalk
    case AnimaWeapon5SpiritTalkParam
    case AnimaWeapon5SpiritTalkType
    case AnimaWeapon5TradeItem
    case AnimaWeaponFUITalk
    case AnimaWeaponFUITalkParam
    case AnimaWeaponIcon
    case AnimaWeaponItem
    case AnimationLOD
    case AozAction
    case AozActionTransient
    case AquariumFish
    case AquariumWater
    case ArchiveItem
    case ArrayEventHandler
    case AttackType
    case Attract
    case Attributive
    case BGM
    case BGMFade
    case BGMFadeType
    case BGMScene
    case BGMSituation
    case BGMSwitch
    case BGMSystemDefine
    case BNpcAnnounceIcon
    case BNpcBase
    case BNpcBasePopVfx
    case BNpcCustomize
    case BNpcName
    case BNpcParts
    case BNpcState
    case BacklightColor
    case Ballista
    case Balloon
    case BankaCraftWorks
    case BankaCraftWorksSupply
    case BannerBg
    case BannerCondition
    case BannerDecoration
    case BannerDesignPreset
    case BannerFacial
    case BannerFrame
    case BannerObtainHintType
    case BannerPreset
    case BannerTimeline
    case BaseParam
    case Battalion
    case BattleLeve
    case BattleLeveRule
    case BeastRankBonus
    case BeastReputationRank
    case BeastTribe
    case Behavior
    case BehaviorMove
    case BehaviorPath
    case BenchmarkCutSceneTable
    case BenchmarkOverrideEquipment
    case BgcArmyAction
    case BgcArmyActionTransient
    case Booster
    case Buddy
    case BuddyAction
    case BuddyEquip
    case BuddyItem
    case BuddyRank
    case BuddySkill
    case CSBonusContent
    case CSBonusContentIdentifier
    case CSBonusContentType
    case CSBonusMission
    case CSBonusMissionType
    case CSBonusSeason
    case CSBonusTextData
    case Cabinet
    case CabinetCategory
    case CabinetSubCategory
    case Calendar
    case Carry
    case Channeling
    case CharaCardBase
    case CharaCardDecoration
    case CharaCardDesignCategory
    case CharaCardDesignPreset
    case CharaCardDesignType
    case CharaCardHeader
    case CharaCardPlayStyle
    case CharaMakeClassEquip
    case CharaMakeCustomize
    case CharaMakeName
    case CharaMakeType
    case ChatBubbleSampeTextList
    case ChatBubbleType
    case ChocoboRace
    case ChocoboRaceAbility
    case ChocoboRaceAbilityType
    case ChocoboRaceCalculateParam
    case ChocoboRaceChallenge
    case ChocoboRaceItem
    case ChocoboRaceRank
    case ChocoboRaceRanking
    case ChocoboRaceStatus
    case ChocoboRaceTerritory
    case ChocoboRaceTutorial
    case ChocoboRaceWeather
    case ChocoboTaxi
    case ChocoboTaxiStand
    case CircleActivity
    case ClassJob
    case ClassJobActionUI
    case ClassJobActionUICategory
    case ClassJobCategory
    case ClassJobResident
    case CollectablesRefine
    case CollectablesShop
    case CollectablesShopItem
    case CollectablesShopItemGroup
    case CollectablesShopRefine
    case CollectablesShopRewardItem
    case CollectablesShopRewardScrip
    case CollisionIdPallet
    case ColorFilter
    case Colosseum
    case ColosseumMatchRank
    case Companion
    case CompanionMove
    case CompanionTransient
    case CompanyAction
    case CompanyCraftDraft
    case CompanyCraftDraftCategory
    case CompanyCraftManufactoryState
    case CompanyCraftPart
    case CompanyCraftProcess
    case CompanyCraftSequence
    case CompanyCraftSupplyItem
    case CompanyCraftType
    case CompanyLeve
    case CompanyLeveRule
    case CompleteJournal
    case CompleteJournalCategory
    case Completion
    case Condition
    case ConfigKey
    case ContentAttributeRect
    case ContentCloseCycle
    case ContentDirectorBattleTalk
    case ContentDirectorManagedSG
    case ContentEffectiveTime
    case ContentEntry
    case ContentEventItem
    case ContentExAction
    case ContentFinderCondition
    case ContentFinderConditionRegion
    case ContentFinderConditionTransient
    case ContentGauge
    case ContentGaugeColor
    case ContentMemberType
    case ContentNpc
    case ContentNpcTalk
    case ContentRandomSelect
    case ContentRewardCondition
    case ContentRoulette
    case ContentRouletteOpenRule
    case ContentRouletteRoleBonus
    case ContentTalk
    case ContentTalkParam
    case ContentTodo
    case ContentTourismConstruct
    case ContentType
    case ContentUICategory
    case ContentsNote
    case ContentsNoteCategory
    case ContentsNoteLevel
    case ContentsNoteRewardEurekaEXP
    case ContentsTutorial
    case ContentsTutorialPage
    case CraftAction
    case CraftActionIndirection
    case CraftLeve
    case CraftLeveTalk
    case CraftType
    case Credit
    case CreditBackImage
    case CreditCast
    case CreditDataSet
    case CreditFont
    case CreditList
    case CreditListText
    case CreditVersion
    case CurrencyScripConvert
    case CustomTalk
    case CustomTalkDefineClient
    case CustomTalkNestHandlers
    case CustomTalkResident
    case CutActionTimeline
    case CutSceneIncompQuest
    case CutScreenImage
    case Cutscene
    case CutsceneActorSize
    case CutsceneEventMotion
    case CutsceneMotion
    case CutsceneName
    case CutsceneWorkIndex
    case CuttingGrass
    case CycleTime
    case DailySupplyItem
    case DawnContent
    case DawnContentParticipable
    case DawnGrowMember
    case DawnMember
    case DawnMemberUIParam
    case DawnQuestMember
    case DeepDungeon
    case DeepDungeon4GimmickEffect
    case DeepDungeon4GimmickEffectTransient
    case DeepDungeonBan
    case DeepDungeonDanger
    case DeepDungeonDemiclone
    case DeepDungeonEquipment
    case DeepDungeonFloorEffectUI
    case DeepDungeonGrowData
    case DeepDungeonHardModeItem
    case DeepDungeonItem
    case DeepDungeonLayer
    case DeepDungeonMagicStone
    case DeepDungeonMap5X
    case DeepDungeonResident
    case DeepDungeonRoom
    case DeepDungeonStatus
    case DefaultTalk
    case DefaultTalkLipSyncType
    case DeliveryQuest
    case Description
    case DescriptionPage
    case DescriptionSection
    case DescriptionStandAlone
    case DescriptionStandAloneTransient
    case DescriptionString
    case DirectorSystemDefine
    case DirectorType
    case DisposalShop
    case DisposalShopFilterType
    case DisposalShopItem
    case DomaStoryProgress
    case DpsChallenge
    case DpsChallengeOfficer
    case DpsChallengeTransient
    case DynamicEvent
    case DynamicEventEnemyType
    case DynamicEventManager
    case DynamicEventSet
    case DynamicEventSingleBattle
    case DynamicEventType
    case DynamicEventUIType
    case ENpcBase
    case ENpcDressUp
    case ENpcDressUpDress
    case ENpcResident
    case EObj
    case EObjName
    case EmjAddon
    case EmjCharaViewCamera
    case EmjCostume
    case EmjCostumeData
    case EmjDani
    case EmjVoiceNpc
    case Emote
    case EmoteCategory
    case EmoteMode
    case EmoteTransient
    case EquipRaceCategory
    case EquipSlotCategory
    case Error
    case Eureka
    case EurekaAetherItem
    case EurekaAethernet
    case EurekaDungeonPortal
    case EurekaGrowData
    case EurekaLogosMixerProbability
    case EurekaMagiaAction
    case EurekaMagiciteItem
    case EurekaMagiciteItemType
    case EurekaSphereElementAdjust
    case EurekaStoryProgress
    case EventAction
    case EventCustomIconType
    case EventExtraConditionSet
    case EventGimmickPathMove
    case EventIconPriority
    case EventIconPriorityPair
    case EventIconType
    case EventItem
    case EventItemCastTimeline
    case EventItemCategory
    case EventItemHelp
    case EventItemTimeline
    case EventMountGimmickPathMove
    case EventPathMove
    case EventSetDefine
    case EventSituationIconTooltip
    case EventSystemDefine
    case EventTutorial
    case EventTutorialPage
    case EventVfx
    case ExHotbarCrossbarIndexType
    case ExVersion
    case ExportedGatheringPoint
    case ExportedSG
    case ExtraCommand
    case FCActivity
    case FCActivityCategory
    case FCAuthority
    case FCAuthorityCategory
    case FCChestName
    case FCCrestSymbol
    case FCDefine
    case FCHierarchy
    case FCProfile
    case FCRank
    case FCReputation
    case FCRights
    case FGSAddon
    case FGSStageUI
    case FashionCheckThemeCategory
    case FashionCheckWeeklyTheme
    case Fate
    case FateEvent
    case FateMode
    case FateProgressUI
    case FateRuleEx
    case FateShop
    case FateTokenType
    case FccShop
    case Festival
    case FieldMarker
    case FishParameter
    case FishParameterReverse
    case FishingBaitParameter
    case FishingNoteInfo
    case FishingRecordType
    case FishingRecordTypeTransient
    case FishingSpot
    case FittingShop
    case FittingShopCategory
    case FittingShopCategoryItem
    case FittingShopItemSet
    case FollowMount
    case Frontline
    case Frontline01
    case Frontline02
    case Frontline03
    case FurnitureCatalogCategory
    case FurnitureCatalogItemList
    case GCRankGridaniaFemaleText
    case GCRankGridaniaMaleText
    case GCRankLimsaFemaleText
    case GCRankLimsaMaleText
    case GCRankUldahFemaleText
    case GCRankUldahMaleText
    case GCScripShopCategory
    case GCScripShopItem
    case GCShop
    case GCShopItemCategory
    case GCSupplyDefine
    case GCSupplyDuty
    case GCSupplyDutyReward
    case GFATE
    case GFateClimbing
    case GFateClimbing2
    case GFateClimbing2Content
    case GFateClimbing2TotemType
    case GFateDance
    case GFateHiddenObject
    case GFateRideShooting
    case GFateRoulette
    case GFateStelth
    case GFateType
    case GameConditionValueArray
    case GameRewardObtainType
    case GardeningSeed
    case GathererCrafterLvAdjustTable
    case GathererCrafterTool
    case GathererReductionReward
    case GatheringCondition
    case GatheringExp
    case GatheringItem
    case GatheringItemLevelConvertTable
    case GatheringItemPoint
    case GatheringLeve
    case GatheringLeveBNpcEntry
    case GatheringLeveRoute
    case GatheringLeveRule
    case GatheringNotebookItem
    case GatheringNotebookList
    case GatheringPoint
    case GatheringPointBase
    case GatheringPointBonus
    case GatheringPointBonusType
    case GatheringPointName
    case GatheringPointTransient
    case GatheringRarePopTimeTable
    case GatheringSubCategory
    case GatheringType
    case GcArmyCandidateCategory
    case GcArmyCapture
    case GcArmyCaptureTactics
    case GcArmyEquipPreset
    case GcArmyExpedition
    case GcArmyExpeditionMemberBonus
    case GcArmyExpeditionTrait
    case GcArmyExpeditionTraitCond
    case GcArmyExpeditionType
    case GcArmyMember
    case GcArmyMemberGrow
    case GcArmyMemberGrowExp
    case GcArmyProgress
    case GcArmyTraining
    case GeneralAction
    case GilShop
    case GilShopInfo
    case GilShopItem
    case GimmickAccessor
    case GimmickBill
    case GimmickJump
    case GimmickRect
    case GimmickTalk
    case GimmickYesNo
    case Glasses
    case GlassesStyle
    case GoldSaucerArcadeMachine
    case GoldSaucerContent
    case GoldSaucerTalk
    case GoldSaucerTextData
    case GrandCompany
    case GrandCompanyRank
    case GroupPoseCharaStatus
    case GroupPoseCharacterShowPreset
    case GroupPoseFrame
    case GroupPoseStamp
    case GroupPoseStampCategory
    case GroupPoseStampFontColor
    case GuardianDeity
    case Guide
    case GuidePage
    case GuidePageString
    case GuideTitle
    case GuildOrder
    case GuildOrderGuide
    case GuildOrderOfficer
    case GuildleveAssignment
    case GuildleveAssignmentCategory
    case GuildleveAssignmentTalk
    case HWDAnnounce
    case HWDCrafterSupply
    case HWDCrafterSupplyReward
    case HWDCrafterSupplyTerm
    case HWDDevLayerControl
    case HWDDevLevelUI
    case HWDDevLevelWebText
    case HWDDevLively
    case HWDDevProgress
    case HWDGathereInspectTerm
    case HWDGathererInspection
    case HWDGathererInspectionReward
    case HWDInfoBoardArticle
    case HWDInfoBoardArticleTransient
    case HWDInfoBoardArticleType
    case HWDInfoBoardBackNumber
    case HWDLevelChangeDeception
    case HWDSharedGroup
    case HWDSharedGroupControlParam
    case HairMakeType
    case HalloweenNpcSelect
    case HouseRetainerPose
    case HousingAethernet
    case HousingAppeal
    case HousingEmploymentNpcList
    case HousingEmploymentNpcRace
    case HousingExterior
    case HousingFurniture
    case HousingIndoorTerritory
    case HousingInterior
    case HousingLandSet
    case HousingMapMarkerInfo
    case HousingMateAuthority
    case HousingMerchantPose
    case HousingPileLimit
    case HousingPlacement
    case HousingPreset
    case HousingRenovation
    case HousingTrainingDoll
    case HousingUnitedExterior
    case HousingUnplacement
    case HousingYardObject
    case HowTo
    case HowToCategory
    case HowToPage
    case Hud
    case HudTransient
    case HugeCraftworksNpc
    case HugeCraftworksRank
    case IKDContentBonus
    case IKDFishParam
    case IKDPlayerMissionCondition
    case IKDRoute
    case IKDRouteTable
    case IKDSpot
    case IKDTimeDefine
    case IconLanguage
    case InclusionShop
    case InclusionShopCategory
    case InclusionShopSeries
    case InclusionShopWelcom
    case InclusionShopWelcomText
    case IndividualWeather
    case InstanceContent
    case InstanceContentBuff
    case InstanceContentGuide
    case InstanceContentQICData
    case InstanceContentRewardItem
    case InstanceContentTextData
    case InstanceContentType
    case Item
    case ItemAction
    case ItemActionTelepo
    case ItemBarterCheck
    case ItemBarterWarning
    case ItemFood
    case ItemLevel
    case ItemOnceHqMasterpiece
    case ItemRepairPrice
    case ItemRepairResource
    case ItemRetainerLevelUp
    case ItemSearchCategory
    case ItemSeries
    case ItemSortCategory
    case ItemSpecialBonus
    case ItemStainCondition
    case ItemUICategory
    case JigsawScore
    case JigsawTimeBonus
    case Jingle
    case JobHudManual
    case JobHudManualPriority
    case JournalCategory
    case JournalGenre
    case JournalSection
    case KineDriverOffGroup
    case Knockback
    case LFGExtensionContent
    case LegacyQuest
    case Leve
    case LeveAssignmentType
    case LeveClient
    case LeveRewardItem
    case LeveRewardItemGroup
    case LeveString
    case LeveSystemDefine
    case LeveVfx
    case Level
    case LinkRace
    case LiveMinigames
    case LiveMinigamesDynamicDefine
    case LiveMinigamesObjectEvent
    case LiveMinigamesTerritoryType
    case LivelyActorGroup
    case LoadingImage
    case LoadingTips
    case LoadingTipsSub
    case Lobby
    case Lockon
    case LogFilter
    case LogKind
    case LogMessage
    case LootModeType
    case LotteryExchangeShop
    case MJIAnimals
    case MJIBuilding
    case MJIBuildingPlace
    case MJICraftworksObject
    case MJICraftworksObjectTheme
    case MJICraftworksPopularity
    case MJICraftworksPopularityType
    case MJICraftworksRankRatio
    case MJICraftworksSupplyDefine
    case MJICraftworksTension
    case MJICropSeed
    case MJIDisposalShopItem
    case MJIDisposalShopUICategory
    case MJIFarmPastureRank
    case MJIFunction
    case MJIGardenscaping
    case MJIGathering
    case MJIGatheringItem
    case MJIGatheringObject
    case MJIGatheringTool
    case MJIHudMode
    case MJIItemCategory
    case MJIItemPouch
    case MJIKeyItem
    case MJILandmark
    case MJILandmarkPlace
    case MJILivelyActor
    case MJIMinionPopAreas
    case MJIName
    case MJINekomimiRequest
    case MJIProgress
    case MJIRank
    case MJIRecipe
    case MJIRecipeMaterial
    case MJIStockyardManagementArea
    case MJIStockyardManagementTable
    case MJIText
    case MJIVillageAppearanceSG
    case MJIVillageAppearanceUI
    case MJIVillageDevelopment
    case MKDBNpcData
    case MKDChain
    case MKDData
    case MKDGrowData
    case MKDGrowDataSJob
    case MKDLore
    case MKDRelicGrowth2Category
    case MKDRelicGrowth2ContentList
    case MKDRelicGrowth2Monster
    case MKDSupportJob
    case MKDTrait
    case MYCTemporaryItem
    case MYCTemporaryItemUICategory
    case MYCWarResultNotebook
    case MacroIcon
    case MacroIconRedirectOld
    case MainCommand
    case MainCommandCategory
    case MandervilleWeaponEnhance
    case Maneuvers
    case ManeuversArmor
    case Map
    case MapCondition
    case MapExclusive
    case MapMarker
    case MapMarkerRegion
    case MapReplace
    case MapSymbol
    case MapTransientPvPMap
    case MapType
    case Marker
    case MassivePcContent
    case MassivePcContentBattleTalk
    case MassivePcContentTextData
    case MassivePcContentTodo
    case MateAuthorityCategory
    case Materia
    case MateriaGrade
    case MateriaJoinRate
    case MateriaJoinRateGatherCraft
    case MateriaParam
    case McGuffin
    case McGuffinUIData
    case MiniGameRA
    case MiniGameRANotes
    case MiniGameTurnBreakAction
    case MiniGameTurnBreakConst
    case MiniGameTurnBreakEnemy
    case MiniGameTurnBreakPop
    case MiniGameTurnBreakPopOffset
    case MiniGameTurnBreakStage
    case MiniGameTurnBreakStatus
    case MinionRace
    case MinionRules
    case MinionSkillType
    case MinionStage
    case MirageStoreSetItem
    case MirageStoreSetItemLookup
    case MobHuntOrder
    case MobHuntOrderType
    case MobHuntReward
    case MobHuntRewardCap
    case MobHuntTarget
    case ModelAttribute
    case ModelChara
    case ModelScale
    case ModelSkeleton
    case ModelState
    case MonsterNote
    case MonsterNoteTarget
    case MotionTimeline
    case MotionTimelineAdvanceBlend
    case MotionTimelineBlendTable
    case Mount
    case MountAction
    case MountCustomize
    case MountFlyingCondition
    case MountSpeed
    case MountTransient
    case MoveControl
    case MoveTimeline
    case MoveVfx
    case MovieStaffList
    case MovieSubtitle
    case MovieSubtitle500
    case MovieSubtitleVoyage
    case MultipleHelp
    case MultipleHelpPage
    case MultipleHelpString
    case NotebookDivision
    case NotebookDivisionCategory
    case NotebookList
    case NotoriousMonster
    case NotoriousMonsterTerritory
    case NpcEquip
    case NpcYell
    case Omen
    case Omikuji
    case OmikujiGuidance
    case OnlineStatus
    case OpenContent
    case OpenContentCandidateName
    case OpenLuaUI
    case Opening
    case OpeningSystemDefine
    case Orchestrion
    case OrchestrionCategory
    case OrchestrionPath
    case OrchestrionUiparam
    case Ornament
    case OrnamentAction
    case OrnamentCustomize
    case OrnamentCustomizeGroup
    case OrnamentTransient
    case ParamGrow
    case PartyContent
    case PartyContentCutscene
    case PartyContentTextData
    case PartyContentTransient
    case PatchMark
    case Perform
    case PerformGroup
    case PerformGuideScore
    case PerformTransient
    case Permission
    case Pet
    case PetAction
    case PetMirage
    case PhysicsGroup
    case PhysicsOffGroup
    case PhysicsParameter
    case PhysicsWind
    case Picture
    case PlaceName
    case PlaceNameReplace
    case PlantPotFlowerSeed
    case Platform
    case PlayerSearchLocation
    case PlayerSearchSubLocation
    case PointMenu
    case PointMenuChoice
    case PointMenuString
    case PreHandler
    case PreHandlerMovement
    case PresetCamera
    case PresetCameraAdjust
    case PreviewableItems
    case PublicContent
    case PublicContentCutscene
    case PublicContentTextData
    case PublicContentType
    case PvPAction
    case PvPActionSort
    case PvPBaseParamValue
    case PvPInitialSelectActionTrait
    case PvPRank
    case PvPRankTransient
    case PvPSelectAction
    case PvPSelectTrait
    case PvPSelectTraitTransient
    case PvPSeries
    case PvPSeriesLevel
    case PvPTrait
    case QTE
    case Quest
    case QuestAcceptAdditionCondition
    case QuestAdditionalToolIcon
    case QuestAroundPlayerHide
    case QuestAroundPlayerHideExt
    case QuestBattle
    case QuestBattleResident
    case QuestBattleSystemDefine
    case QuestChapter
    case QuestClassJobReward
    case QuestClassJobSupply
    case QuestCustomTodo
    case QuestDefineClient
    case QuestDerivedClass
    case QuestEffect
    case QuestEffectDefine
    case QuestEffectType
    case QuestEquipModel
    case QuestEventAreaEntranceInfo
    case QuestHideReward
    case QuestLinkMarker
    case QuestLinkMarkerIcon
    case QuestLinkMarkerSet
    case QuestRecomplete
    case QuestRedo
    case QuestRedoChapter
    case QuestRedoChapterUI
    case QuestRedoChapterUICategory
    case QuestRedoChapterUITab
    case QuestRedoIncompChapter
    case QuestRedoValidCustomTalk
    case QuestRepeatFlag
    case QuestRewardOther
    case QuestSceneAbortCondition
    case QuestSceneAbortConditionFlag
    case QuestSceneAbortConditionType
    case QuestSelectTitle
    case QuestSetDefine
    case QuestStatusParam
    case QuestSubCommand
    case QuestSystemDefine
    case QuickChat
    case QuickChatTransient
    case RPParameter
    case Race
    case RacingChocoboGrade
    case RacingChocoboItem
    case RacingChocoboName
    case RacingChocoboNameCategory
    case RacingChocoboNameInfo
    case RacingChocoboParam
    case RaidFinderParam
    case ReactionEventObject
    case ReactionEventObjectInfo
    case RecastNavimesh
    case Recipe
    case RecipeLevelTable
    case RecipeLookup
    case RecipeNotebookList
    case RecipeSubCategory
    case RecommendContents
    case Relic
    case Relic3
    case Relic3Materia
    case Relic3Rate
    case Relic3RatePattern
    case Relic6Magicite
    case RelicItem
    case RelicMateria
    case RelicNote
    case RelicNoteCategory
    case ReplaceAction
    case Resident
    case ResidentMotionType
    case ResistanceWeaponAdjust
    case RetainerFortuneRewardRange
    case RetainerTask
    case RetainerTaskLvRange
    case RetainerTaskNormal
    case RetainerTaskParameter
    case RetainerTaskParameterLvDiff
    case RetainerTaskRandom
    case RideShooting
    case RideShootingScheduler
    case RideShootingTarget
    case RideShootingTargetScheduler
    case RideShootingTargetType
    case RideShootingTextData
    case Role
    case SE
    case SEBattle
    case SatisfactionArbitration
    case SatisfactionBonusGuarantee
    case SatisfactionNpc
    case SatisfactionSupply
    case SatisfactionSupplyReward
    case SatisfactionSupplyRewardExp
    case ScenarioTree
    case ScenarioTreeTips
    case ScenarioTreeTipsClassQuest
    case ScenarioType
    case ScreenImage
    case SecretRecipeBook
    case SecretRecipeBookGroup
    case SequentialEvent
    case SequentialEventMultipleRange
    case SharlayanCraftWorks
    case SharlayanCraftWorksSupply
    case ShellFixedFromCommand
    case Skirmish
    case SkyIsland
    case SkyIsland2
    case SkyIsland2Mission
    case SkyIsland2MissionDetail
    case SkyIsland2MissionType
    case SkyIsland2RangeType
    case SkyIslandMapMarker
    case SkyIslandSubject
    case Snipe
    case SnipeCollision
    case SnipeElementId
    case SnipeHitEvent
    case SnipePerformanceCamera
    case SnipeTalk
    case SnipeTalkName
    case SpearfishingComboTarget
    case SpearfishingEcology
    case SpearfishingItem
    case SpearfishingItemReverse
    case SpearfishingNotebook
    case SpearfishingRecordPage
    case SpearfishingSilhouette
    case SpecialShop
    case SpecialShopItemCategory
    case Spectator
    case Stain
    case StainTransient
    case StanceChange
    case Status
    case StatusHitEffect
    case StatusLoopVFX
    case Story
    case StorySystemDefine
    case SubmarineExploration
    case SubmarineExplorationLog
    case SubmarineMap
    case SubmarinePart
    case SubmarineRank
    case SubmarineSpecCategory
    case SwitchTalk
    case SwitchTalkVariation
    case SystemGraphicPreset
    case TelepoRelay
    case TerritoryAethernet
    case TerritoryAetheryteList
    case TerritoryCandidates
    case TerritoryChatRule
    case TerritoryIntendedUse
    case TerritoryType
    case TerritoryTypeTelepo
    case TerritoryTypeTransient
    case TextCommand
    case TextCommandParam
    case TiltParam
    case Title
    case TofuBg
    case TofuEditParam
    case TofuObject
    case TofuObjectCategory
    case TofuPreset
    case TofuPresetCategory
    case TofuPresetObject
    case TomestoneConvert
    case Tomestones
    case TomestonesItem
    case TopicSelect
    case Town
    case TradeScreenImage
    case Trait
    case TraitRecast
    case TraitTransient
    case Transformation
    case Treasure
    case TreasureHuntRank
    case TreasureHuntTexture
    case TreasureModel
    case TreasureSpot
    case Tribe
    case TriggerEffect
    case TripleTriad
    case TripleTriadCard
    case TripleTriadCardObtain
    case TripleTriadCardRarity
    case TripleTriadCardResident
    case TripleTriadCardType
    case TripleTriadCompetition
    case TripleTriadDefine
    case TripleTriadResident
    case TripleTriadRule
    case TripleTriadTournament
    case Tutorial
    case TutorialDPS
    case TutorialGimmick
    case TutorialHealer
    case TutorialTank
    case UDS_Event
    case UDS_Object
    case UDS_Property
    case UDS_Stats
    case UIColor
    case UIColorPickerTable
    case UIConst
    case UILevelLookup
    case VFX
    case VVDData
    case VVDNotebookContents
    case VVDNotebookSeries
    case VVDRouteData
    case VVDVariantAction
    case VVDVoteRoute
    case VVDVoteRouteLabel
    case ValentionSweetsMaterial
    case ValentionSweetsRecipe
    case Vase
    case VaseFlower
    case WKSAchievement
    case WKSAchievementDailyDefine
    case WKSAchievementRewardItem
    case WKSAethernet
    case WKSAetheryte
    case WKSAetheryteList
    case WKSAetheryteObjectGroup
    case WKSCosmoToolClass
    case WKSCosmoToolCommonLevel
    case WKSCosmoToolDataAmount
    case WKSCosmoToolName
    case WKSCosmoToolPassiveBuff
    case WKSCosmoToolUIRandomMsg
    case WKSDevGrade
    case WKSDevGradeBGSet
    case WKSEmergencyInfo
    case WKSEmergencyInfoText
    case WKSEmergencyMission
    case WKSEmergencyMissionGroup
    case WKSEmergencyProblem
    case WKSFateControl
    case WKSFortunePatternUIColorSet
    case WKSFortunePatternUIPlace
    case WKSFortunePrizeGrade
    case WKSFortuneSPPatternUIPlace
    case WKSFunction
    case WKSItemInfo
    case WKSItemSubCategory
    case WKSMechaEventData
    case WKSMechaEventObject
    case WKSMechaEventObjectGroup
    case WKSMechaEventRewardUI
    case WKSMechaFieldSearcher
    case WKSMechaLivelyActorGroup
    case WKSMissionInfo
    case WKSMissionLotteryCond
    case WKSMissionLotterySpecialCond
    case WKSMissionMapMarker
    case WKSMissionPromotionCondition
    case WKSMissionRecipe
    case WKSMissionReward
    case WKSMissionSupplyItem
    case WKSMissionText
    case WKSMissionToDo
    case WKSMissionToDoEvalutionItem
    case WKSMissionToDoEvalutionRefin
    case WKSMissionToDoSuccessType
    case WKSMissionUnit
    case WKSNextPlanetGuidance
    case WKSParam
    case WKSPioneeringTrail
    case WKSPioneeringTrailString
    case WKSPlanetSelect
    case WKSPraiseHologram
    case WKSPraiseUI
    case WKSScoreList
    case WKSSharedGroup
    case WKSTerritoryInfo
    case WKSText
    case WKSTreasure
    case WKSTreasureInfo
    case WKSWarp
    case WKSZoneFloorCollision
    case Warp
    case WarpCondition
    case WarpLogic
    case WeaponTimeline
    case Weather
    case WeatherGroup
    case WeatherRate
    case WeatherReportReplace
    case WebGuidance
    case WebURL
    case WeddingBGM
    case WeddingFlowerColor
    case WeddingPlan
    case WeeklyBingoMultipleOrder
    case WeeklyBingoOrderData
    case WeeklyBingoRewardData
    case WeeklyBingoText
    case WeeklyLotBonus
    case WeeklyLotBonusThreshold
    case World
    case WorldDCGroupType
    case XPVPGroupActivity
    case YKW
    case YardCatalogCategory
    case YardCatalogItemList
    case ZoneSharedGroup
    case ZoneTimeline
}
